<?php
$svc = [
    'title'       => 'Dermatology',
    'tagline'     => 'Skin, Hair & Cosmetic Care',
    'description' => 'Our Dermatology department offers expert diagnosis and treatment for all skin, hair, and nail conditions. From medical dermatology to advanced cosmetic procedures, our board-certified dermatologists combine science and aesthetics for outstanding results.',
    'heroImage'   => '../../images/Doctors/Dermatologist.jpg',
    'icon'        => 'fa-spa',
    'badge'       => 'Dermatology Department',
    'color'       => '#0d7377',
    'colorLight'  => '#e6f7f7',
    'imgBadge'    => '✓ Board-Certified Dermatologists',
    'stats' => [
        ['15k+','Skin Treatments'],
        ['8+',  'Specialist Doctors'],
        ['98%', 'Patient Satisfaction'],
        ['200+','Cosmetic Procedures'],
    ],
    'features' => [
        'Diagnosis and treatment of 100+ skin conditions',
        'Advanced laser treatments and chemical peels',
        'Hair loss analysis and PRP therapy',
        'Acne, psoriasis, eczema treatment protocols',
        'Mole mapping and skin cancer screening',
        'Personalised skincare regimen planning',
    ],
    'services' => [
        ['icon'=>'fa-magnifying-glass', 'title'=>'Skin Cancer Screening',     'desc'=>'Advanced dermoscopy and mole mapping for early detection of melanoma and other skin cancers.'],
        ['icon'=>'fa-face-smile',       'title'=>'Acne & Scar Treatment',     'desc'=>'Medical and laser-based treatments for active acne, scars, and post-inflammatory hyperpigmentation.'],
        ['icon'=>'fa-wand-magic-sparkles','title'=>'Cosmetic Dermatology',    'desc'=>'Botox, dermal fillers, PRP facials, and skin rejuvenation procedures.'],
        ['icon'=>'fa-person-rays',      'title'=>'Laser Therapy',             'desc'=>'State-of-the-art laser treatments for hair removal, pigmentation, and skin resurfacing.'],
        ['icon'=>'fa-head-side',        'title'=>'Hair & Scalp Disorders',    'desc'=>'Diagnosis and treatment of alopecia, dandruff, scalp psoriasis, and hair thinning.'],
        ['icon'=>'fa-shield',           'title'=>'Allergy & Eczema Care',     'desc'=>'Patch testing, allergy identification, and comprehensive eczema/dermatitis management.'],
    ],
    'steps' => [
        ['title'=>'Consultation',      'desc'=>'Discuss your skin concerns with our specialist and get a personalised diagnosis.'],
        ['title'=>'Diagnosis',         'desc'=>'Advanced tools like dermoscopy, UV light analysis, and skin biopsy if needed.'],
        ['title'=>'Treatment Plan',    'desc'=>'Receive a tailored treatment protocol — medical, procedural, or cosmetic.'],
        ['title'=>'Procedure / Therapy','desc'=>'Same-day or scheduled treatments performed in our state-of-the-art procedure rooms.'],
        ['title'=>'Aftercare',         'desc'=>'Detailed aftercare instructions and follow-up to ensure optimal results.'],
    ],
    'conditions' => [
        ['icon'=>'fa-face-tired',    'label'=>'Acne & Pimples'],
        ['icon'=>'fa-droplet',       'label'=>'Eczema / Atopic Dermatitis'],
        ['icon'=>'fa-sun',           'label'=>'Psoriasis'],
        ['icon'=>'fa-circle-dot',    'label'=>'Vitiligo'],
        ['icon'=>'fa-head-side',     'label'=>'Hair Loss (Alopecia)'],
        ['icon'=>'fa-virus',         'label'=>'Fungal Infections'],
        ['icon'=>'fa-circle-xmark',  'label'=>'Warts & Molluscum'],
        ['icon'=>'fa-face-smile',    'label'=>'Melasma & Pigmentation'],
        ['icon'=>'fa-triangle-exclamation','label'=>'Skin Allergies / Hives'],
        ['icon'=>'fa-radiation',     'label'=>'Skin Cancer Screening'],
    ],
    'testimonials' => [
        ['text'=>'"My acne scars of 5 years are almost invisible after the laser treatment. The dermatologist explained everything patiently and the results exceeded expectations."', 'name'=>'Sneha Kulkarni', 'role'=>'Student, Aurangabad', 'init'=>'S'],
        ['text'=>'"I struggled with psoriasis for years. SmartCare\'s dermatology team put me on the correct treatment and my skin has never been better."', 'name'=>'Vikram Desai', 'role'=>'Teacher, Nagpur', 'init'=>'V'],
        ['text'=>'"The cosmetic procedures are done so professionally. I got a subtle, natural look with the fillers. Highly recommend Dr. Thomas\'s team."', 'name'=>'Meera Agarwal', 'role'=>'Entrepreneur, Mumbai', 'init'=>'M'],
    ],
    'faqs' => [
        ['q'=>'Is cosmetic dermatology safe?', 'a'=>'Yes, when performed by a board-certified dermatologist using approved products and techniques. We follow international safety protocols for every procedure.'],
        ['q'=>'How many sessions are needed for laser hair removal?', 'a'=>'Typically 6–8 sessions spaced 4–6 weeks apart, depending on hair type, skin tone, and treatment area.'],
        ['q'=>'Will my insurance cover dermatology visits?', 'a'=>'Medical dermatology visits (acne, eczema, psoriasis, etc.) are generally covered. Cosmetic procedures are usually out-of-pocket. Check with your insurer.'],
        ['q'=>'Can children visit the dermatology department?', 'a'=>'Absolutely. We treat patients of all ages, including infants with nappy rash, childhood eczema, and atopic dermatitis.'],
    ],
];
include '../../Includes/service_page.php';
