<?php
$svc = [
    'title'       => 'Emergency Care',
    'tagline'     => '24/7 Critical & Trauma Emergency Services',
    'description' => 'Our Emergency department operates 24 hours a day, 7 days a week, with a dedicated trauma bay, resuscitation room, and specialist on-call system. We are equipped to handle every medical emergency — from accidents to cardiac arrest — with speed and precision.',
    'heroImage'   => '../../images/Doctors/emergency.jpg',
    'icon'        => 'fa-truck-medical',
    'badge'       => 'Emergency & Trauma Department',
    'color'       => '#0d7377',
    'colorLight'  => '#e6f7f7',
    'imgBadge'    => '✓ Level 1 Trauma Centre',
    'stats' => [
        ['24/7', 'Round-the-Clock Care'],
        ['< 5min','Triage Response Time'],
        ['30+',  'Emergency Specialists'],
        ['98%',  'Survival Rate'],
    ],
    'features' => [
        '24/7 emergency triage with 5-minute response time',
        'Dedicated polytrauma bay and resuscitation room',
        'On-call specialists across all major specialties',
        'Advanced life support and ventilator capability',
        'Fast-track emergency imaging (CT, X-ray, USG)',
        'Direct escalation to ICU, OT, or cath lab',
    ],
    'services' => [
        ['icon'=>'fa-heart-crack',       'title'=>'Cardiac Emergencies',      'desc'=>'STEMI door-to-balloon < 60 min, defibrillation, CPR, and cardiac resuscitation protocols.'],
        ['icon'=>'fa-person-falling',    'title'=>'Trauma & Accidents',       'desc'=>'Polytrauma management with ATLS protocol, haemostasis, and emergency surgery.'],
        ['icon'=>'fa-brain',             'title'=>'Stroke Response',          'desc'=>'Stroke code activation with CT, thrombolysis, and neuro-intervention within 45 minutes.'],
        ['icon'=>'fa-lungs-virus',       'title'=>'Respiratory Emergencies',  'desc'=>'Severe asthma, COPD exacerbation, pulmonary embolism, and respiratory failure management.'],
        ['icon'=>'fa-child',             'title'=>'Paediatric Emergency',     'desc'=>'Dedicated paediatric emergency bay with child-specific protocols and weight-based dosing.'],
        ['icon'=>'fa-virus',             'title'=>'Sepsis & Infections',      'desc'=>'Sepsis bundle activation, early antibiotics, and organ support for life-threatening infections.'],
    ],
    'steps' => [
        ['title'=>'Arrival & Triage',    'desc'=>'Immediate triage by a trained nurse within 2 minutes using the MTS system.'],
        ['title'=>'Stabilisation',       'desc'=>'ABC approach — airway, breathing, and circulation secured immediately.'],
        ['title'=>'Diagnostics',         'desc'=>'Point-of-care tests, emergency imaging, and specialist consultation.'],
        ['title'=>'Definitive Treatment','desc'=>'Medical management, interventional procedure, or emergency surgery.'],
        ['title'=>'Admission / Discharge','desc'=>'ICU, ward admission, or safe discharge with follow-up plan.'],
    ],
    'conditions' => [
        ['icon'=>'fa-heart-crack',       'label'=>'Heart Attack / STEMI'],
        ['icon'=>'fa-brain',             'label'=>'Stroke'],
        ['icon'=>'fa-person-falling',    'label'=>'Accidents & Polytrauma'],
        ['icon'=>'fa-face-dizzy',        'label'=>'Unconsciousness / Collapse'],
        ['icon'=>'fa-lungs',             'label'=>'Breathing Difficulty'],
        ['icon'=>'fa-droplet',           'label'=>'Diabetic Emergency'],
        ['icon'=>'fa-skull-crossbones',  'label'=>'Poisoning / Overdose'],
        ['icon'=>'fa-fire',              'label'=>'Burns & Chemical Injuries'],
        ['icon'=>'fa-baby',              'label'=>'Obstetric Emergencies'],
        ['icon'=>'fa-bolt',              'label'=>'Seizures / Status Epilepticus'],
    ],
    'testimonials' => [
        ['text'=>'"My husband was brought in with a heart attack at 2 AM. The team saved his life — door to balloon time was under 50 minutes. We are forever grateful."', 'name'=>'Geeta Mohan', 'role'=>'Homemaker, Nagpur', 'init'=>'G'],
        ['text'=>'"My daughter\'s anaphylaxis was managed within minutes of arrival. The paediatric ER team was calm, fast, and incredibly reassuring for us parents."', 'name'=>'Sachin Pawar', 'role'=>'IT Professional, Pune', 'init'=>'S'],
        ['text'=>'"Admitted after a road accident with multiple injuries. The emergency and surgical teams worked seamlessly. Excellent coordination and care."', 'name'=>'Rohan Yadav', 'role'=>'Teacher, Nashik', 'init'=>'R'],
    ],
    'faqs' => [
        ['q'=>'When should I call an ambulance vs. drive to the ER?', 'a'=>'Call an ambulance for chest pain, stroke symptoms, major accidents, unconsciousness, or severe breathing difficulty. For ambulance, dial 108. Driving to ER is acceptable for less severe emergencies.'],
        ['q'=>'What is a triage system?', 'a'=>'Triage is the process of sorting patients by urgency. Red (immediate) patients are seen within seconds, orange within 10 minutes, yellow within 30 minutes, and green as soon as possible.'],
        ['q'=>'Does the emergency department operate on holidays?', 'a'=>'Our Emergency department is fully staffed 24 hours a day, 365 days a year including all public holidays, weekends, and festivals.'],
        ['q'=>'What should I bring to the ER?', 'a'=>'Bring any available medical records, a list of medications, and ID/insurance card if possible. If the situation is critical, focus on getting to the hospital — paperwork can wait.'],
    ],
];
include '../../Includes/service_page.php';
