<?php
$svc = [
    'title'       => 'Hospital Services',
    'tagline'     => 'Complete Inpatient & Multi-Specialty Hospital Care',
    'description' => 'SmartCare Hospital provides world-class inpatient, day-care, and outpatient services across 25+ specialties. Our state-of-the-art infrastructure, skilled nursing team, and patient-first philosophy ensure the highest standards of care under one roof.',
    'heroImage'   => '../../images/bgHospital.jpg',
    'icon'        => 'fa-hospital',
    'badge'       => 'Multi-Specialty Hospital',
    'color'       => '#0d7377',
    'colorLight'  => '#e6f7f7',
    'imgBadge'    => '✓ NABH Accredited Hospital',
    'stats' => [
        ['500+',  'Beds'],
        ['25+',   'Specialties'],
        ['300+',  'Specialists'],
        ['50k+',  'Patients Annually'],
    ],
    'features' => [
        'NABH accredited with international patient safety standards',
        'Advanced modular OT complex — 12 operation theatres',
        'Medical, surgical, and cardiac ICUs',
        'Private, semi-private, and general ward options',
        'Cashless insurance across 200+ TPA networks',
        '24/7 pharmacy, blood bank, and laboratory',
    ],
    'services' => [
        ['icon'=>'fa-bed',              'title'=>'Inpatient Admission',       'desc'=>'Private, semi-private, and general ward hospitalisations with round-the-clock nursing care.'],
        ['icon'=>'fa-scissors',         'title'=>'Surgical Services',         'desc'=>'Laparoscopic, robotic, and open surgeries across general, ortho, cardiac, and neuro surgery.'],
        ['icon'=>'fa-monitor-heart-rate','title'=>'Intensive Care (ICU)',     'desc'=>'Medical ICU, cardiac care unit, neonatal ICU, and surgical ICU with 1:1 nurse-to-patient ratio.'],
        ['icon'=>'fa-flask',            'title'=>'Laboratory & Imaging',      'desc'=>'In-house NABL lab, digital X-ray, CT, MRI, PET-CT, and ultrasound available 24/7.'],
        ['icon'=>'fa-person-walking',   'title'=>'Physiotherapy & Rehab',    'desc'=>'In-patient and outpatient physiotherapy, respiratory therapy, and stroke rehabilitation.'],
        ['icon'=>'fa-credit-card',      'title'=>'Cashless Insurance',        'desc'=>'Tie-ups with 200+ insurance companies and TPA networks for hassle-free cashless hospitalisation.'],
    ],
    'steps' => [
        ['title'=>'Planned Admission',   'desc'=>'Pre-admission counselling, insurance pre-authorisation, and bed booking in advance.'],
        ['title'=>'Admission Process',   'desc'=>'Quick check-in at our admission desk with room allotment and care team assignment.'],
        ['title'=>'Inpatient Care',      'desc'=>'Specialist visits, nursing care, diagnostics, and procedures as per treatment plan.'],
        ['title'=>'Discharge Planning',  'desc'=>'Discharge summary, medication plan, follow-up dates, and home care instructions.'],
        ['title'=>'Insurance Settlement','desc'=>'Dedicated insurance desk handles all TPA coordination and billing queries.'],
    ],
    'conditions' => [
        ['icon'=>'fa-scissors',         'label'=>'General & Laparoscopic Surgery'],
        ['icon'=>'fa-heart',            'label'=>'Cardiac Surgeries & Interventions'],
        ['icon'=>'fa-brain',            'label'=>'Neurosurgery'],
        ['icon'=>'fa-bone',             'label'=>'Orthopaedic Surgeries'],
        ['icon'=>'fa-baby',             'label'=>'Obstetrics & Neonatal Care'],
        ['icon'=>'fa-lungs',            'label'=>'Pulmonology & Respiratory'],
        ['icon'=>'fa-circle',           'label'=>'Oncology (Cancer) Treatment'],
        ['icon'=>'fa-kidney',           'label'=>'Urology & Nephrology'],
        ['icon'=>'fa-virus',            'label'=>'Infectious Disease Management'],
        ['icon'=>'fa-eye',              'label'=>'Ophthalmology & ENT'],
    ],
    'testimonials' => [
        ['text'=>'"From admission to discharge, every team member — from doctors to housekeeping — was professional and compassionate. SmartCare genuinely cares."', 'name'=>'Mrs. Shalini Varma', 'role'=>'Hyderabad', 'init'=>'S'],
        ['text'=>'"The cashless insurance process was completely smooth. The TPA desk handled everything and I didn\'t pay a single rupee out of pocket."', 'name'=>'Ashok Tiwari', 'role'=>'Government Employee, Bhopal', 'init'=>'A'],
        ['text'=>'"The NICU team took exceptional care of our premature baby for 6 weeks. Their dedication and communication with our family was outstanding."', 'name'=>'Neha & Sunil Joshi', 'role'=>'Pune', 'init'=>'N'],
    ],
    'faqs' => [
        ['q'=>'How do I get admitted to the hospital?', 'a'=>'For planned admissions, visit the admission desk with your doctor\'s reference letter and insurance card. For emergencies, proceed directly to the Emergency department — admission is initiated from there.'],
        ['q'=>'Which insurance companies are accepted?', 'a'=>'We are empanelled with 200+ insurance companies and TPAs including Star Health, HDFC Ergo, New India, Niva Bupa, and all government schemes (CGHS, ECHS, Ayushman Bharat).'],
        ['q'=>'Are visiting hours restricted?', 'a'=>'General visiting hours are 11AM–1PM and 5PM–7PM. ICU visits are permitted for one close relative at specified times. Patient welfare and infection control guide all visiting policies.'],
        ['q'=>'Can I request a specific doctor or surgeon?', 'a'=>'Yes, you can request a specific specialist for your care. We will accommodate your preference subject to the doctor\'s availability and case appropriateness.'],
    ],
];
include '../../Includes/service_page.php';
