<?php
$svc = [
    'title'       => 'Laboratory & Diagnostics',
    'tagline'     => 'Accurate. Fast. Certified.',
    'description' => 'Our NABL-accredited laboratory provides a comprehensive range of pathology, biochemistry, microbiology, and molecular diagnostic tests. With same-day reports and home sample collection, we make diagnostics convenient and reliable.',
    'heroImage'   => '../../images/Doctors/laboratory.jpg',
    'icon'        => 'fa-flask',
    'badge'       => 'Laboratory & Diagnostics',
    'color'       => '#0d7377',
    'colorLight'  => '#e6f7f7',
    'imgBadge'    => '✓ NABL Accredited Laboratory',
    'stats' => [
        ['500+', 'Tests Available'],
        ['98.9%','Diagnostic Accuracy'],
        ['4hr',  'Average Report Time'],
        ['Home', 'Sample Collection'],
    ],
    'features' => [
        'NABL-accredited with international quality standards',
        'Over 500 diagnostic tests across all specialties',
        'Home sample collection at your convenience',
        'Digital reports delivered via email and app',
        'Same-day reports for most routine panels',
        'Expert pathologist review for all reports',
    ],
    'services' => [
        ['icon'=>'fa-droplet',         'title'=>'Haematology',               'desc'=>'CBC, ESR, peripheral smear, coagulation studies, and bone marrow analysis.'],
        ['icon'=>'fa-flask',           'title'=>'Biochemistry',              'desc'=>'Liver, kidney, thyroid, lipid, blood sugar, and electrolyte panels.'],
        ['icon'=>'fa-virus',           'title'=>'Microbiology & Culture',    'desc'=>'Blood, urine, pus, and sputum cultures with antibiotic sensitivity testing.'],
        ['icon'=>'fa-dna',             'title'=>'Molecular Diagnostics',     'desc'=>'PCR, RT-PCR, FISH, and next-generation sequencing for genetic and infectious diseases.'],
        ['icon'=>'fa-magnifying-glass','title'=>'Histopathology / Biopsy',   'desc'=>'Tissue examination by an expert pathologist for cancer diagnosis and grading.'],
        ['icon'=>'fa-home',            'title'=>'Home Sample Collection',    'desc'=>'Book a sample collection at your home between 6AM–9AM for early morning fasting tests.'],
    ],
    'steps' => [
        ['title'=>'Book a Test',         'desc'=>'Order online, via our app, or at the lab reception. Home collection available.'],
        ['title'=>'Sample Collection',   'desc'=>'Phlebotomist collects your sample — blood, urine, swab — at lab or home.'],
        ['title'=>'Analysis',            'desc'=>'Samples analysed on automated, quality-controlled, NABL-certified analysers.'],
        ['title'=>'Pathologist Review',  'desc'=>'All reports reviewed and validated by a qualified pathologist.'],
        ['title'=>'Receive Report',      'desc'=>'Reports delivered digitally via email, WhatsApp, or patient portal.'],
    ],
    'conditions' => [
        ['icon'=>'fa-droplet',           'label'=>'Diabetes (HbA1c, FBS, PPBS)'],
        ['icon'=>'fa-heart',             'label'=>'Cardiac Markers (Troponin, CK-MB)'],
        ['icon'=>'fa-filter',            'label'=>'Kidney Function Tests'],
        ['icon'=>'fa-circle',            'label'=>'Liver Function Tests'],
        ['icon'=>'fa-shield-virus',      'label'=>'Thyroid Profile (T3, T4, TSH)'],
        ['icon'=>'fa-virus',             'label'=>'Infection Cultures & PCR'],
        ['icon'=>'fa-dna',               'label'=>'Genetic & Cancer Markers'],
        ['icon'=>'fa-chart-bar',         'label'=>'Lipid Profile'],
        ['icon'=>'fa-vial',              'label'=>'Vitamin D & B12'],
        ['icon'=>'fa-person-pregnant',   'label'=>'Antenatal & Fertility Panel'],
    ],
    'testimonials' => [
        ['text'=>'"Home sample collection at 6:30 AM, reports on WhatsApp by noon. The fastest, most convenient lab service I have ever used."', 'name'=>'Amit Kulkarni', 'role'=>'CA, Pune', 'init'=>'A'],
        ['text'=>'"The histopathology report for my biopsy was detailed and clear. The pathologist called me personally to explain the findings — above and beyond."', 'name'=>'Dr. Usha Patel', 'role'=>'GP, Ahmedabad', 'init'=>'U'],
        ['text'=>'"Accurate, fast, and honest. No unnecessary tests pushed. My family uses SmartCare lab for all our annual health check panels."', 'name'=>'Vikram Nair', 'role'=>'Banker, Mumbai', 'init'=>'V'],
    ],
    'faqs' => [
        ['q'=>'Do I need to fast before blood tests?', 'a'=>'Fasting is required for blood sugar, lipid profile, and some other tests. A 10–12 hour overnight fast is recommended. You can drink water. Other tests do not require fasting.'],
        ['q'=>'How soon will I get my reports?', 'a'=>'Most routine blood tests are reported within 4–6 hours. Culture tests take 2–5 days. Histopathology typically takes 5–7 working days.'],
        ['q'=>'Is home sample collection available every day?', 'a'=>'Yes, home collection is available 7 days a week from 6 AM to 9 AM. Book the previous evening for next-morning collection.'],
        ['q'=>'Can I collect my own sample for a urine or stool test?', 'a'=>'Yes. We provide sterile collection containers. Instructions for proper sample collection will be given at the time of booking.'],
    ],
];
include '../../Includes/service_page.php';
